using System.Collections.Generic;
using StuartWilliams.CandyCo.SharedKernels.Models;

namespace StuartWilliams.CandyCo.SharedKernels.Lookups
{
    /// <summary>
    /// List: ISO 4217 Curency Code
    /// </summary>
    public static class CurencyCodeList
    {

        /// <summary>
        /// List of Codes
        /// </summary>
        public static readonly Dictionary<string, CurrencyInfo> Iso4217 = new() {
            { "AED", new CurrencyInfo("AED","784",2,"United Arab Emirates dirham","ar-AE")},
            { "AFN", new CurrencyInfo("AFN","971",2,"Afghan afghani","ps-AF")},
            { "ALL", new CurrencyInfo("ALL", "8", 2, "Albanian lek","sq-AL")},
            { "AMD", new CurrencyInfo("AMD", "51", 2, "Armenian dram","hy-AM")},
            { "ANG", new CurrencyInfo("ANG", "532", 2, "Netherlands Antillean guilder","nl-NL")},
            { "AOA", new CurrencyInfo("AOA", "973", 2, "Angolan kwanza","pt-AO")},
            { "ARS", new CurrencyInfo("ARS", "32", 2, "Argentine peso","es-AR")},
            { "AUD", new CurrencyInfo("AUD", "36", 2, "Australian dollar","en-AU")},
            { "AWG", new CurrencyInfo("AWG", "533", 2, "Aruban florin","nl-AW")},
            { "AZN", new CurrencyInfo("AZN", "944", 2, "Azerbaijani manat","az-AZ")},
            { "BAM", new CurrencyInfo("BAM", "977", 2, "Bosnia and Herzegovina convertible mark","hr-BA")},
            { "BBD", new CurrencyInfo("BBD", "52", 2, "Barbados dollar","en-BB")},
            { "BDT", new CurrencyInfo("BDT", "50", 2, "Bangladeshi taka","bn-BD")},
            { "BGN", new CurrencyInfo("BGN", "975", 2, "Bulgarian lev","bg-BG")},
            { "BHD", new CurrencyInfo("BHD", "48", 3, "Bahraini dinar","ar-BH")},
            { "BIF", new CurrencyInfo("BIF", "108", 0, "Burundian franc","rn-BL")},
            { "BMD", new CurrencyInfo("BMD", "60", 2, "Bermudian dollar","en-BM")},
            { "BND", new CurrencyInfo("BND", "96", 2, "Brunei dollar","ms-BN")},
            { "BOB", new CurrencyInfo("BOB", "68", 2, "Boliviano","es-BO")},
            //{ "BOV", new CurrencyInfo("BOV", "984", 2, "Bolivian Mvdol (funds code)","")},
            { "BRL", new CurrencyInfo("BRL", "986", 2, "Brazilian real","pt-BR")},
            { "BSD", new CurrencyInfo("BSD", "44", 2, "Bahamian dollar","en-BS")},
            { "BTN", new CurrencyInfo("BTN", "64", 2, "Bhutanese ngultrum","dz-BT")},
            { "BWP", new CurrencyInfo("BWP", "72", 2, "Botswana pula","en-BW")},
            { "BYN", new CurrencyInfo("BYN", "933", 2, "Belarusian ruble","be-BY")},
            { "BZD", new CurrencyInfo("BZD", "84", 2, "Belize dollar","en-BZ")},
            { "CAD", new CurrencyInfo("CAD", "124", 2, "Canadian dollar","en-CA")},
            { "CDF", new CurrencyInfo("CDF", "976", 2, "Congolese franc","fr-CD")},
            //{ "CHE", new CurrencyInfo("CHE", "947", 2, "WIR euro (complementary currency)","")},
            //{ "CHF", new CurrencyInfo("CHF", "756", 2, "Swiss franc","")},
            //{ "CHW", new CurrencyInfo("CHW", "948", 2, "WIR franc (complementary currency)","")},
            //{ "CLF", new CurrencyInfo("CLF", "990", 4, "Unidad de Fomento (funds code)","")},
            { "CLP", new CurrencyInfo("CLP", "152", 0, "Chilean peso","es-CL")},
            { "COP", new CurrencyInfo("COP", "170", 2, "Colombian peso","es-CO")},
            //{ "COU", new CurrencyInfo("COU", "970", 2, "Unidad de Valor Real (UVR) (funds code)[9]","")},
            { "CRC", new CurrencyInfo("CRC", "188", 2, "Costa Rican colon","es-CR")},
            //{ "CUC", new CurrencyInfo("CUC", "931", 2, "Cuban convertible peso","")},
            { "CUP", new CurrencyInfo("CUP", "192", 2, "Cuban peso","es-CU")},
            { "CVE", new CurrencyInfo("CVE", "132", 2, "Cape Verdean escudo","pt-CV")},
            { "CZK", new CurrencyInfo("CZK", "203", 2, "Czech koruna","cs-CZ")},
            { "DJF", new CurrencyInfo("DJF", "262", 0, "Djiboutian franc","ar-DJ")},
            { "DKK", new CurrencyInfo("DKK", "208", 2, "Danish krone","da-DK")},
            { "DOP", new CurrencyInfo("DOP", "214", 2, "Dominican peso","es-DO")},
            { "DZD", new CurrencyInfo("DZD",  "12", 2, "Algerian dinar","ar-DZ")},
            { "EGP", new CurrencyInfo("EGP", "818", 2, "Egyptian pound","ar-EG")},
            { "ERN", new CurrencyInfo("ERN", "232", 2, "Eritrean nakfa","en-ER")},
            { "ETB", new CurrencyInfo("ETB", "230", 2, "Ethiopian birr","om-ET")},
            { "EUR", new CurrencyInfo("EUR", "978", 2, "Euro","eu")},
            { "FJD", new CurrencyInfo("FJD", "242", 2, "Fiji dollar","en-FJ")},
            { "FKP", new CurrencyInfo("FKP", "238", 2, "Falkland Islands pound","en-FK")},
            { "GBP", new CurrencyInfo("GBP", "826", 2, "Pound sterling","en-BR")},
            { "GEL", new CurrencyInfo("GEL", "981", 2, "Georgian lari","ka-GE")},
            { "GHS", new CurrencyInfo("GHS", "936", 2, "Ghanaian cedi","en-GH")},
            { "GIP", new CurrencyInfo("GIP", "292", 2, "Gibraltar pound","en-GI")},
            { "GMD", new CurrencyInfo("GMD", "270", 2, "Gambian dalasi", "en-GM")},
            { "GNF", new CurrencyInfo("GNF", "324", 0, "Guinean franc","fr-GN")},
            { "GTQ", new CurrencyInfo("GTQ", "320", 2, "Guatemalan quetzal","es-GT")},
            { "GYD", new CurrencyInfo("GYD", "328", 2, "Guyanese dollar","en-GY")},
            { "HKD", new CurrencyInfo("HKD", "344", 2, "Hong Kong dollar","zh-HK")},
            { "HNL", new CurrencyInfo("HNL", "340", 2, "Honduran lempira","es-HN")},
            { "HRK", new CurrencyInfo("HRK", "191", 2, "Croatian kuna","hr-HR")},
            { "HTG", new CurrencyInfo("HTG", "332", 2, "Haitian gourde","fr-HT")},
            { "HUF", new CurrencyInfo("HUF", "348", 2, "Hungarian forint","hu-HU")},
            { "IDR", new CurrencyInfo("IDR", "360", 2, "Indonesian rupiah","id-ID")},
            { "ILS", new CurrencyInfo("ILS", "376", 2, "Israeli new shekel","he-IL")},
            { "INR", new CurrencyInfo("INR", "356", 2, "Indian rupee","en-IN")},
            //{ "IQD", new CurrencyInfo("IQD", "368", 3, "Iraqi dinar","")},
            //{ "IRR", new CurrencyInfo("IRR", "364", 2, "Iranian rial","")},
            { "ISK", new CurrencyInfo("ISK", "352", 0, "Icelandic króna (plural: krónur)","is-IS")},
            { "JMD", new CurrencyInfo("JMD", "388", 2, "Jamaican dollar","en-JM")},
            { "JOD", new CurrencyInfo("JOD", "400", 3, "Jordanian dinar","ar-JO")},
            { "JPY", new CurrencyInfo("JPY", "392", 0, "Japanese yen","ja-JP")},
            { "KES", new CurrencyInfo("KES", "404", 2, "Kenyan shilling","en-KE")},
            { "KGS", new CurrencyInfo("KGS", "417", 2, "Kyrgyzstani som","ky-KG")},
            { "KHR", new CurrencyInfo("KHR", "116", 2, "Cambodian riel","km-KH")},
            { "KMF", new CurrencyInfo("KMF", "174", 0, "Comoro franc","ar-KM")},
            //{ "KPW", new CurrencyInfo("KPW", "408", 2, "North Korean won","")},
            { "KRW", new CurrencyInfo("KRW", "410", 0, "South Korean won","ko-KR")},
            { "KWD", new CurrencyInfo("KWD", "414", 3, "Kuwaiti dinar","ar-KW")},
            { "KYD", new CurrencyInfo("KYD", "136", 2, "Cayman Islands dollar","en-KY")},
            { "KZT", new CurrencyInfo("KZT", "398", 2, "Kazakhstani tenge","kk-KZ")},
            { "LAK", new CurrencyInfo("LAK", "418", 2, "Lao kip", "lo-LA")},
            { "LBP", new CurrencyInfo("LBP", "422", 2, "Lebanese pound", "ar-LB")},
            { "LKR", new CurrencyInfo("LKR", "144", 2, "Sri Lankan rupee", "si-LK")},
            { "LRD", new CurrencyInfo("LRD", "430", 2, "Liberian dollar", "en-LR")},
            { "LSL", new CurrencyInfo("LSL", "426", 2, "Lesotho loti", "en-LS")},
            //{ "LYD", new CurrencyInfo("LYD", "434", 3, "Libyan dinar", "")},
            { "MAD", new CurrencyInfo("MAD", "504", 2, "Moroccan dirham", "fr-MA")},
            { "MDL", new CurrencyInfo("MDL", "498", 2, "Moldovan leu", "ro-MD")},
            { "MGA", new CurrencyInfo("MGA", "969", 2, "Malagasy ariary", "mg-MG")},
            { "MKD", new CurrencyInfo("MKD", "807", 2, "Macedonian denar", "mk-MK")},
            //{ "MMK", new CurrencyInfo("MMK", "104", 2, "Myanmar kyat", "")},
            { "MNT", new CurrencyInfo("MNT", "496", 2, "Mongolian tögrög", "mn-MN")},
            { "MOP", new CurrencyInfo("MOP", "446", 2, "Macanese pataca", "en-MO")},
            { "MRU", new CurrencyInfo("MRU", "929", 2, "Mauritanian ouguiya","")},
            { "MUR", new CurrencyInfo("MUR", "480", 2, "Mauritian rupee", "en-MU")},
            { "MVR", new CurrencyInfo("MVR", "462", 2, "Maldivian rufiyaa", "en-MV")},
            { "MWK", new CurrencyInfo("MWK", "454", 2, "Malawian kwacha", "en-MW")},
            { "MXN", new CurrencyInfo("MXN", "484", 2, "Mexican peso", "sp-MX")},
            //{ "MXV", new CurrencyInfo("MXV", "979", 2, "Mexican Unidad de Inversion (UDI) (funds code)", "")},
            { "MYR", new CurrencyInfo("MYR", "458", 2, "Malaysian ringgit", "en-MY")},
            { "MZN", new CurrencyInfo("MZN", "943", 2, "Mozambican metical", "pt-MZ")},
            { "NAD", new CurrencyInfo("NAD", "516", 2, "Namibian dollar", "af-NA")},
            { "NGN", new CurrencyInfo("NGN", "566", 2, "Nigerian naira", "en-NG")},
            { "NIO", new CurrencyInfo("NIO", "558", 2, "Nicaraguan córdoba", "es-NI")},
            { "NOK", new CurrencyInfo("NOK", "578", 2, "Norwegian krone", "nb-NO")},
            { "NPR", new CurrencyInfo("NPR", "524", 2, "Nepalese rupee", "ne-NP")},
            { "NZD", new CurrencyInfo("NZD", "554", 2, "New Zealand dollar", "en-NZ")},
            { "OMR", new CurrencyInfo("OMR", "512", 3, "Omani rial","ar-OM")},
            { "PAB", new CurrencyInfo("PAB", "590", 2, "Panamanian balboa", "es-PA")},
            { "PEN", new CurrencyInfo("PEN", "604", 2, "Peruvian sol", "es-PE")},
            { "PGK", new CurrencyInfo("PGK", "598", 2, "Papua New Guinean kina", "en-PG")},
            { "PHP", new CurrencyInfo("PHP", "608", 2, "Philippine peso", "en-PH")},
            { "PKR", new CurrencyInfo("PKR", "586", 2, "Pakistani rupee","ar-PK")},
            { "PLN", new CurrencyInfo("PLN", "985", 2, "Polish złoty","pl-PL")},
            { "PYG", new CurrencyInfo("PYG", "600", 0, "Paraguayan guaraní", "es-PY")},
            { "QAR", new CurrencyInfo("QAR", "634", 2, "Qatari riyal", "ar-QA")},
            { "RON", new CurrencyInfo("RON", "946", 2, "Romanian leu", "ro-RO")},
            { "RSD", new CurrencyInfo("RSD", "941", 2, "Serbian dinar","sr-RS")},
            //{ "CNY", new CurrencyInfo("CNY", "156", 2, "Renminbi", "")},
            { "RUB", new CurrencyInfo("RUB", "643", 2, "Russian ruble", "rs-RS")},
            { "RWF", new CurrencyInfo("RWF", "646", 0, "Rwandan franc", "rw-RW")},
            { "SAR", new CurrencyInfo("SAR", "682", 2, "Saudi riyal", "ar-SA")},
            { "SBD", new CurrencyInfo("SBD", "90", 2, "Solomon Islands dollar", "en-SB")},
            { "SCR", new CurrencyInfo("SCR", "690", 2, "Seychelles rupee", "en-SC")},
            { "SDG", new CurrencyInfo("SDG", "938", 2, "Sudanese pound", "en-SD")},
            { "SEK", new CurrencyInfo("SEK", "752", 2, "Swedish krona (plural: kronor)", "sv-SE")},
            { "SGD", new CurrencyInfo("SGD", "702", 2, "Singapore dollar", "en-SG")},
            { "SHP", new CurrencyInfo("SHP", "654", 2, "Saint Helena pound", "en-SH")},
            { "SLE", new CurrencyInfo("SLE", "925", 2, "Sierra Leonean leone (new leone)", "en-SL")},
            //{ "SLL", new CurrencyInfo("SLL", "694", 2, "Sierra Leonean leone (old leone)", "")},
            { "SOS", new CurrencyInfo("SOS", "706", 2, "Somali shilling", "so-SO")},
            { "SRD", new CurrencyInfo("SRD", "968", 2, "Surinamese dollar", "nl-SR")},
            { "SSP", new CurrencyInfo("SSP", "728", 2, "South Sudanese pound", "en-SS")},
            { "STN", new CurrencyInfo("STN", "930", 2, "São Tomé and Príncipe dobra", "pt-ST")},
            { "SVC", new CurrencyInfo("SVC", "222", 2, "Salvadoran colón", "es-SV")},
            { "SYP", new CurrencyInfo("SYP", "760", 2, "Syrian pound", "ar-SY")},
            { "SZL", new CurrencyInfo("SZL", "748", 2, "Swazi lilangeni", "en-SZ")},
            { "THB", new CurrencyInfo("THB", "764", 2, "Thai baht", "th-TH")},
            { "TJS", new CurrencyInfo("TJS", "972", 2, "Tajikistani somoni", "tg-TJ")},
            { "TMT", new CurrencyInfo("TMT", "934", 2, "Turkmenistan manat", "tk-TM")},
            { "TND", new CurrencyInfo("TND", "788", 3, "Tunisian dinar","ar-TN")},
            { "TOP", new CurrencyInfo("TOP", "776", 2, "Tongan paʻanga", "to-TO")},
            { "TRY", new CurrencyInfo("TRY", "949", 2, "Turkish lira","tr-TR")},
            { "TTD", new CurrencyInfo("TTD", "780", 2, "Trinidad and Tobago dollar", "")},
            { "TWD", new CurrencyInfo("TWD", "901", 2, "New Taiwan dollar", "en-TT")},
            { "TZS", new CurrencyInfo("TZS", "834", 2, "Tanzanian shilling", "en-TZ")},
            { "UAH", new CurrencyInfo("UAH", "980", 2, "Ukrainian hryvnia", "uk-UA")},
            { "UGX", new CurrencyInfo("UGX", "800", 0, "Ugandan shilling", "en-UG")},
            { "USD", new CurrencyInfo("USD", "840", 2, "United States dollar", "en-US")},
            //{ "USN", new CurrencyInfo("USN", "997", 2, "United States dollar (next day) (funds code)", "")},
            //{ "UYI", new CurrencyInfo("UYI", "940", 0, "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)", "")},
            { "UYU", new CurrencyInfo("UYU", "858", 2, "Uruguayan peso", "es-UY")},
            //{ "UYW", new CurrencyInfo("UYW", "927", 4, "Unidad previsional", "")},
            { "UZS", new CurrencyInfo("UZS", "860", 2, "Uzbekistan sum", "uz-UZ")},
            //{ "VED", new CurrencyInfo("VED", "926", 2, "Venezuelan digital bolívar", "")},
            { "VES", new CurrencyInfo("VES", "928", 2, "Venezuelan sovereign bolívar", "es-VE")},
            { "VND", new CurrencyInfo("VND", "704", 0, "Vietnamese đồng", "vi-VN")},
            { "VUV", new CurrencyInfo("VUV", "548", 0, "Vanuatu vatu", "un-VU")},
            { "WST", new CurrencyInfo("WST", "882", 2, "Samoan tala", "en-AS")},
            //{ "XAF", new CurrencyInfo("XAF", "950", 0, "CFA franc BEAC", "")},
            //{ "XAG", new CurrencyInfo("XAG", "961", 0, "Silver (one troy ounce)", "")},
            //{ "XAU", new CurrencyInfo("XAU", "959", 0, "Gold (one troy ounce)", "")},
            //{ "XBA", new CurrencyInfo("XBA", "955", 0, "European Composite Unit (EURCO) (bond market unit)", "")},
            //{ "XBB", new CurrencyInfo("XBB", "956", 0, "European Monetary Unit (E.M.U.-6) (bond market unit)", "")},
            //{ "XBC", new CurrencyInfo("XBC", "957", 0, "European Unit of Account 9 (E.U.A.-9) (bond market unit)", "")},
            //{ "XBD", new CurrencyInfo("XBD", "958", 0, "European Unit of Account 17 (E.U.A.-17) (bond market unit)", "")},
            //{ "XCD", new CurrencyInfo("XCD", "951", 2, "East Caribbean dollar", "")},
            //{ "XDR", new CurrencyInfo("XDR", "960", 0, "Special drawing rights", "")},
            //{ "XOF", new CurrencyInfo("XOF", "952", 0, "CFA franc BCEAO", "")},
            //{ "XPD", new CurrencyInfo("XPD", "964", 0, "Palladium (one troy ounce)", "")},
            //{ "XPF", new CurrencyInfo("XPF", "953", 0, "CFP franc (franc Pacifique)", "")},
            //{ "XPT", new CurrencyInfo("XPT", "962", 0, "Platinum (one troy ounce)", "")},
            //{ "XSU", new CurrencyInfo("XSU", "994", 0, "SUCRE", "")},
            //{ "XTS", new CurrencyInfo("XTS", "963", 0, "Code reserved for testing", "")},
            //{ "XUA", new CurrencyInfo("XUA", "965", 0, "ADB Unit of Account", "")},
            { "XXX", new CurrencyInfo("XXX", "999", 0, "No currency", "")},
            { "YER", new CurrencyInfo("YER", "886", 2, "Yemeni rial", "ar-YI")},
            { "ZAR", new CurrencyInfo("ZAR", "710", 2, "South African rand", "af-ZA")},
            { "ZMW", new CurrencyInfo("ZMW", "967", 2, "Zambian kwacha", "en-ZM")},
            { "ZWL", new CurrencyInfo("ZWL", "932", 2, "Zimbabwean dollar", "en-ZW")}
        };

    }
}
