using System.Collections.Generic;
using StuartWilliams.CandyCo.SharedKernels.Models;

namespace StuartWilliams.CandyCo.SharedKernels.Lookups
{
    /// <summary>
    /// List: ISO 4217 Curency Code
    /// </summary>
    public static class CurencyCodeList
    {

        /// <summary>
        /// List of Codes
        /// </summary>
        public static readonly Dictionary<string, CurrencyInfo> Iso4217 = new() {
            { "AED", new CurrencyInfo("AED","784",2,"United Arab Emirates dirham")},
            { "AFN", new CurrencyInfo("AFN","971",2,"Afghan afghani")},
            { "ALL", new CurrencyInfo("ALL", "8", 2, "Albanian lek")},
            { "AMD", new CurrencyInfo("AMD", "51", 2, "Armenian dram")},
            { "ANG", new CurrencyInfo("ANG", "532", 2, "Netherlands Antillean guilder")},
            { "AOA", new CurrencyInfo("AOA", "973", 2, "Angolan kwanza")},
            { "ARS", new CurrencyInfo("ARS", "32", 2, "Argentine peso")},
            { "AUD", new CurrencyInfo("AUD", "36", 2, "Australian dollar")},
            { "AWG", new CurrencyInfo("AWG", "533", 2, "Aruban florin")},
            { "AZN", new CurrencyInfo("AZN", "944", 2, "Azerbaijani manat")},
            { "BAM", new CurrencyInfo("BAM", "977", 2, "Bosnia and Herzegovina convertible mark")},
            { "BBD", new CurrencyInfo("BBD", "52", 2, "Barbados dollar")},
            { "BDT", new CurrencyInfo("BDT", "50", 2, "Bangladeshi taka")},
            { "BGN", new CurrencyInfo("BGN", "975", 2, "Bulgarian lev")},
            { "BHD", new CurrencyInfo("BHD", "48", 3, "Bahraini dinar")},
            { "BIF", new CurrencyInfo("BIF", "108", 0, "Burundian franc")},
            { "BMD", new CurrencyInfo("BMD", "60", 2, "Bermudian dollar")},
            { "BND", new CurrencyInfo("BND", "96", 2, "Brunei dollar")},
            { "BOB", new CurrencyInfo("BOB", "68", 2, "Boliviano")},
            { "BOV", new CurrencyInfo("BOV", "984", 2, "Bolivian Mvdol (funds code)")},
            { "BRL", new CurrencyInfo("BRL", "986", 2, "Brazilian real")},
            { "BSD", new CurrencyInfo("BSD", "44", 2, "Bahamian dollar")},
            { "BTN", new CurrencyInfo("BTN", "64", 2, "Bhutanese ngultrum")},
            { "BWP", new CurrencyInfo("BWP", "72", 2, "Botswana pula")},
            { "BYN", new CurrencyInfo("BYN", "933", 2, "Belarusian ruble")},
            { "BZD", new CurrencyInfo("BZD", "84", 2, "Belize dollar")},
            { "CAD", new CurrencyInfo("CAD", "124", 2, "Canadian dollar")},
            { "CDF", new CurrencyInfo("CDF", "976", 2, "Congolese franc")},
            { "CHE", new CurrencyInfo("CHE", "947", 2, "WIR euro (complementary currency)")},
            { "CHF", new CurrencyInfo("CHF", "756", 2, "Swiss franc")},
            { "CHW", new CurrencyInfo("CHW", "948", 2, "WIR franc (complementary currency)")},
            { "CLF", new CurrencyInfo("CLF", "990", 4, "Unidad de Fomento (funds code)")},
            { "CLP", new CurrencyInfo("CLP", "152", 0, "Chilean peso")},
            { "COP", new CurrencyInfo("COP", "170", 2, "Colombian peso")},
            { "COU", new CurrencyInfo("COU", "970", 2, "Unidad de Valor Real (UVR) (funds code)[9]")},
            { "CRC", new CurrencyInfo("CRC", "188", 2, "Costa Rican colon")},
            { "CUC", new CurrencyInfo("CUC", "931", 2, "Cuban convertible peso")},
            { "CUP", new CurrencyInfo("CUP", "192", 2, "Cuban peso")},
            { "CVE", new CurrencyInfo("CVE", "132", 2, "Cape Verdean escudo")},
            { "CZK", new CurrencyInfo("CZK", "203", 2, "Czech koruna")},
            { "DJF", new CurrencyInfo("DJF", "262", 0, "Djiboutian franc")},
            { "DKK", new CurrencyInfo("DKK", "208", 2, "Danish krone")},
            { "DOP", new CurrencyInfo("DOP", "214", 2, "Dominican peso")},
            { "DZD", new CurrencyInfo("DZD", "12", 2, "Algerian dinar")},
            { "EGP", new CurrencyInfo("EGP", "818", 2, "Egyptian pound")},
            { "ERN", new CurrencyInfo("ERN", "232", 2, "Eritrean nakfa")},
            { "ETB", new CurrencyInfo("ETB", "230", 2, "Ethiopian birr")},
            { "EUR", new CurrencyInfo("EUR", "978", 2, "Euro")},
            { "FJD", new CurrencyInfo("FJD", "242", 2, "Fiji dollar")},
            { "FKP", new CurrencyInfo("FKP", "238", 2, "Falkland Islands pound")},
            { "GBP", new CurrencyInfo("GBP", "826", 2, "Pound sterling")},
            { "GEL", new CurrencyInfo("GEL", "981", 2, "Georgian lari")},
            { "GHS", new CurrencyInfo("GHS", "936", 2, "Ghanaian cedi")},
            { "GIP", new CurrencyInfo("GIP", "292", 2, "Gibraltar pound")},
            { "GMD", new CurrencyInfo("GMD", "270", 2, "Gambian dalasi")},
            { "GNF", new CurrencyInfo("GNF", "324", 0, "Guinean franc")},
            { "GTQ", new CurrencyInfo("GTQ", "320", 2, "Guatemalan quetzal")},
            { "GYD", new CurrencyInfo("GYD", "328", 2, "Guyanese dollar")},
            { "HKD", new CurrencyInfo("HKD", "344", 2, "Hong Kong dollar")},
            { "HNL", new CurrencyInfo("HNL", "340", 2, "Honduran lempira")},
            { "HRK", new CurrencyInfo("HRK", "191", 2, "Croatian kuna")},
            { "HTG", new CurrencyInfo("HTG", "332", 2, "Haitian gourde")},
            { "HUF", new CurrencyInfo("HUF", "348", 2, "Hungarian forint")},
            { "IDR", new CurrencyInfo("IDR", "360", 2, "Indonesian rupiah")},
            { "ILS", new CurrencyInfo("ILS", "376", 2, "Israeli new shekel")},
            { "INR", new CurrencyInfo("INR", "356", 2, "Indian rupee")},
            { "IQD", new CurrencyInfo("IQD", "368", 3, "Iraqi dinar")},
            { "IRR", new CurrencyInfo("IRR", "364", 2, "Iranian rial")},
            { "ISK", new CurrencyInfo("ISK", "352", 0, "Icelandic króna (plural: krónur)")},
            { "JMD", new CurrencyInfo("JMD", "388", 2, "Jamaican dollar")},
            { "JOD", new CurrencyInfo("JOD", "400", 3, "Jordanian dinar")},
            { "JPY", new CurrencyInfo("JPY", "392", 0, "Japanese yen")},
            { "KES", new CurrencyInfo("KES", "404", 2, "Kenyan shilling")},
            { "KGS", new CurrencyInfo("KGS", "417", 2, "Kyrgyzstani som")},
            { "KHR", new CurrencyInfo("KHR", "116", 2, "Cambodian riel")},
            { "KMF", new CurrencyInfo("KMF", "174", 0, "Comoro franc")},
            { "KPW", new CurrencyInfo("KPW", "408", 2, "North Korean won")},
            { "KRW", new CurrencyInfo("KRW", "410", 0, "South Korean won")},
            { "KWD", new CurrencyInfo("KWD", "414", 3, "Kuwaiti dinar")},
            { "KYD", new CurrencyInfo("KYD", "136", 2, "Cayman Islands dollar")},
            { "KZT", new CurrencyInfo("KZT", "398", 2, "Kazakhstani tenge")},
            { "LAK", new CurrencyInfo("LAK", "418", 2, "Lao kip")},
            { "LBP", new CurrencyInfo("LBP", "422", 2, "Lebanese pound")},
            { "LKR", new CurrencyInfo("LKR", "144", 2, "Sri Lankan rupee")},
            { "LRD", new CurrencyInfo("LRD", "430", 2, "Liberian dollar")},
            { "LSL", new CurrencyInfo("LSL", "426", 2, "Lesotho loti")},
            { "LYD", new CurrencyInfo("LYD", "434", 3, "Libyan dinar")},
            { "MAD", new CurrencyInfo("MAD", "504", 2, "Moroccan dirham")},
            { "MDL", new CurrencyInfo("MDL", "498", 2, "Moldovan leu")},
            { "MGA", new CurrencyInfo("MGA", "969", 2, "Malagasy ariary")},
            { "MKD", new CurrencyInfo("MKD", "807", 2, "Macedonian denar")},
            { "MMK", new CurrencyInfo("MMK", "104", 2, "Myanmar kyat")},
            { "MNT", new CurrencyInfo("MNT", "496", 2, "Mongolian tögrög")},
            { "MOP", new CurrencyInfo("MOP", "446", 2, "Macanese pataca")},
            { "MRU", new CurrencyInfo("MRU", "929", 2, "Mauritanian ouguiya")},
            { "MUR", new CurrencyInfo("MUR", "480", 2, "Mauritian rupee")},
            { "MVR", new CurrencyInfo("MVR", "462", 2, "Maldivian rufiyaa")},
            { "MWK", new CurrencyInfo("MWK", "454", 2, "Malawian kwacha")},
            { "MXN", new CurrencyInfo("MXN", "484", 2, "Mexican peso")},
            { "MXV", new CurrencyInfo("MXV", "979", 2, "Mexican Unidad de Inversion (UDI) (funds code)")},
            { "MYR", new CurrencyInfo("MYR", "458", 2, "Malaysian ringgit")},
            { "MZN", new CurrencyInfo("MZN", "943", 2, "Mozambican metical")},
            { "NAD", new CurrencyInfo("NAD", "516", 2, "Namibian dollar")},
            { "NGN", new CurrencyInfo("NGN", "566", 2, "Nigerian naira")},
            { "NIO", new CurrencyInfo("NIO", "558", 2, "Nicaraguan córdoba")},
            { "NOK", new CurrencyInfo("NOK", "578", 2, "Norwegian krone")},
            { "NPR", new CurrencyInfo("NPR", "524", 2, "Nepalese rupee")},
            { "NZD", new CurrencyInfo("NZD", "554", 2, "New Zealand dollar")},
            { "OMR", new CurrencyInfo("OMR", "512", 3, "Omani rial")},
            { "PAB", new CurrencyInfo("PAB", "590", 2, "Panamanian balboa")},
            { "PEN", new CurrencyInfo("PEN", "604", 2, "Peruvian sol")},
            { "PGK", new CurrencyInfo("PGK", "598", 2, "Papua New Guinean kina")},
            { "PHP", new CurrencyInfo("PHP", "608", 2, "Philippine peso[13]")},
            { "PKR", new CurrencyInfo("PKR", "586", 2, "Pakistani rupee")},
            { "PLN", new CurrencyInfo("PLN", "985", 2, "Polish złoty")},
            { "PYG", new CurrencyInfo("PYG", "600", 0, "Paraguayan guaraní")},
            { "QAR", new CurrencyInfo("QAR", "634", 2, "Qatari riyal")},
            { "RON", new CurrencyInfo("RON", "946", 2, "Romanian leu")},
            { "RSD", new CurrencyInfo("RSD", "941", 2, "Serbian dinar")},
            { "CNY", new CurrencyInfo("CNY", "156", 2, "Renminbi[14]")},
            { "RUB", new CurrencyInfo("RUB", "643", 2, "Russian ruble")},
            { "RWF", new CurrencyInfo("RWF", "646", 0, "Rwandan franc")},
            { "SAR", new CurrencyInfo("SAR", "682", 2, "Saudi riyal")},
            { "SBD", new CurrencyInfo("SBD", "90", 2, "Solomon Islands dollar")},
            { "SCR", new CurrencyInfo("SCR", "690", 2, "Seychelles rupee")},
            { "SDG", new CurrencyInfo("SDG", "938", 2, "Sudanese pound")},
            { "SEK", new CurrencyInfo("SEK", "752", 2, "Swedish krona (plural: kronor)")},
            { "SGD", new CurrencyInfo("SGD", "702", 2, "Singapore dollar")},
            { "SHP", new CurrencyInfo("SHP", "654", 2, "Saint Helena pound")},
            { "SLE", new CurrencyInfo("SLE", "925", 2, "Sierra Leonean leone (new leone)[15][16][17]")},
            { "SLL", new CurrencyInfo("SLL", "694", 2, "Sierra Leonean leone (old leone)[15][16][17]")},
            { "SOS", new CurrencyInfo("SOS", "706", 2, "Somali shilling")},
            { "SRD", new CurrencyInfo("SRD", "968", 2, "Surinamese dollar")},
            { "SSP", new CurrencyInfo("SSP", "728", 2, "South Sudanese pound")},
            { "STN", new CurrencyInfo("STN", "930", 2, "São Tomé and Príncipe dobra")},
            { "SVC", new CurrencyInfo("SVC", "222", 2, "Salvadoran colón")},
            { "SYP", new CurrencyInfo("SYP", "760", 2, "Syrian pound")},
            { "SZL", new CurrencyInfo("SZL", "748", 2, "Swazi lilangeni")},
            { "THB", new CurrencyInfo("THB", "764", 2, "Thai baht")},
            { "TJS", new CurrencyInfo("TJS", "972", 2, "Tajikistani somoni")},
            { "TMT", new CurrencyInfo("TMT", "934", 2, "Turkmenistan manat")},
            { "TND", new CurrencyInfo("TND", "788", 3, "Tunisian dinar")},
            { "TOP", new CurrencyInfo("TOP", "776", 2, "Tongan paʻanga")},
            { "TRY", new CurrencyInfo("TRY", "949", 2, "Turkish lira")},
            { "TTD", new CurrencyInfo("TTD", "780", 2, "Trinidad and Tobago dollar")},
            { "TWD", new CurrencyInfo("TWD", "901", 2, "New Taiwan dollar")},
            { "TZS", new CurrencyInfo("TZS", "834", 2, "Tanzanian shilling")},
            { "UAH", new CurrencyInfo("UAH", "980", 2, "Ukrainian hryvnia")},
            { "UGX", new CurrencyInfo("UGX", "800", 0, "Ugandan shilling")},
            { "USD", new CurrencyInfo("USD", "840", 2, "United States dollar")},
            { "USN", new CurrencyInfo("USN", "997", 2, "United States dollar (next day) (funds code)")},
            { "UYI", new CurrencyInfo("UYI", "940", 0, "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)")},
            { "UYU", new CurrencyInfo("UYU", "858", 2, "Uruguayan peso")},
            { "UYW", new CurrencyInfo("UYW", "927", 4, "Unidad previsional[19]")},
            { "UZS", new CurrencyInfo("UZS", "860", 2, "Uzbekistan sum")},
            { "VED", new CurrencyInfo("VED", "926", 2, "Venezuelan digital bolívar[20]")},
            { "VES", new CurrencyInfo("VES", "928", 2, "Venezuelan sovereign bolívar[13]")},
            { "VND", new CurrencyInfo("VND", "704", 0, "Vietnamese đồng")},
            { "VUV", new CurrencyInfo("VUV", "548", 0, "Vanuatu vatu")},
            { "WST", new CurrencyInfo("WST", "882", 2, "Samoan tala")},
            { "XAF", new CurrencyInfo("XAF", "950", 0, "CFA franc BEAC")},
            { "XAG", new CurrencyInfo("XAG", "961", 0, "Silver (one troy ounce)")},
            { "XAU", new CurrencyInfo("XAU", "959", 0, "Gold (one troy ounce)")},
            { "XBA", new CurrencyInfo("XBA", "955", 0, "European Composite Unit (EURCO) (bond market unit)")},
            { "XBB", new CurrencyInfo("XBB", "956", 0, "European Monetary Unit (E.M.U.-6) (bond market unit)")},
            { "XBC", new CurrencyInfo("XBC", "957", 0, "European Unit of Account 9 (E.U.A.-9) (bond market unit)")},
            { "XBD", new CurrencyInfo("XBD", "958", 0, "European Unit of Account 17 (E.U.A.-17) (bond market unit)")},
            { "XCD", new CurrencyInfo("XCD", "951", 2, "East Caribbean dollar")},
            { "XDR", new CurrencyInfo("XDR", "960", 0, "Special drawing rights")},
            { "XOF", new CurrencyInfo("XOF", "952", 0, "CFA franc BCEAO")},
            { "XPD", new CurrencyInfo("XPD", "964", 0, "Palladium (one troy ounce)")},
            { "XPF", new CurrencyInfo("XPF", "953", 0, "CFP franc (franc Pacifique)")},
            { "XPT", new CurrencyInfo("XPT", "962", 0, "Platinum (one troy ounce)")},
            { "XSU", new CurrencyInfo("XSU", "994", 0, "SUCRE")},
            { "XTS", new CurrencyInfo("XTS", "963", 0, "Code reserved for testing")},
            { "XUA", new CurrencyInfo("XUA", "965", 0, "ADB Unit of Account")},
            { "XXX", new CurrencyInfo("XXX", "999", 0, "No currency")},
            { "YER", new CurrencyInfo("YER", "886", 2, "Yemeni rial")},
            { "ZAR", new CurrencyInfo("ZAR", "710", 2, "South African rand")},
            { "ZMW", new CurrencyInfo("ZMW", "967", 2, "Zambian kwacha")},
            { "ZWL", new CurrencyInfo("ZWL", "932", 2, "Zimbabwean dollar")}
        };

    }
}
